BEGIN
BEGIN TRY
BEGIN TRANSACTION
/* INSERT QUERY HERE */


COMMIT TRANSACTION
END TRY

BEGIN CATCH
ROLLBACK TRANSACTION

SELECT
ERROR_NUMBER() AS ErrorNumber,
ERROR_SEVERITY() AS ErrorSeverity,
ERROR_STATE() AS ErrorState,
ERROR_PROCEDURE() AS ErrorProcedure,
ERROR_LINE() AS ErrorLine,
ERROR_MESSAGE() AS ErrorMessage

END CATCH

END