BEGIN
DECLARE @ID INT, @COLUMN1 VARCHAR(50), @COLUMN2 VARCHAR(50);
 
DECLARE MyCursor CURSOR
    LOCAL
    FAST_FORWARD
    READ_ONLY
    FOR SELECT ID, COLUMN1, COLUMN2FROM #TEST
    ORDER BY ID
 
OPEN MyCURSOR
 
SELECT CURRENT_TIMESTAMP AS 'BEGIN CURSOR'
 
WHILE 1=1
BEGIN
    FETCH MyCURSOR INTO @ID, @COLUMN1, @COLUMN2
 
    IF @@FETCH_STATUS <> 0 BREAK
    --CURSOR PROCESSING HERE
    
END
 
SELECT CURRENT_TIMESTAMP AS 'END CURSOR'
 
CLOSE MyCURSOR;
DEALLOCATE MyCURSOR;
END
